configfile: "config/config.yaml"


rule all:
    input:
        "results/test.txt",
        "results/test.fasta",
        "results/merged_files.bam"

rule make_dag:
    output:
        "images/dag.png"
    shell:
        "snakemake -c4 --dag | dot -Tpng > images/dag.png"

rule clean:
    shell:
        "rm -rf results/"


include: "rules/download_http.smk"
include: "rules/download_ncbi.smk"
include: "rules/merge.smk"

